from pydantic import BaseModel,Field,ValidationError
from datetime import datetime

class UserMessage(BaseModel):
    """Model representing a user message."""
    user_id: int = Field(..., description="The unique identifier of the user")
    message: str = Field(..., description="The message content from the user")
    timestamp: str = Field(..., description="The timestamp when the message was sent")

class AgentResponse(BaseModel):
    """Model representing a response from the agent."""
    response: str = Field(..., description="The response content generated by the agent")
    timestamp: datetime = Field(default_factory=datetime.timezone.utc, description="The timestamp when the response was generated")