from pydantic import BaseModel,Field
from datetime import datetime, timezone

class UserMessage(BaseModel):
    """Model representing a user message."""
    user_id: str = Field(..., description="The unique identifier of the user", example="user_12345")
    session_id: str = Field(..., description="The unique identifier of the session", example="session_67890")
    message: str = Field(..., description="The message content from the user")
    timestamp: str = Field(..., description="The timestamp when the message was sent")

class AgentResponse(BaseModel):
    """Model representing a response from the agent."""
    response: str = Field(..., description="The response content generated by the agent")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="The timestamp when the response was generated")